### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by ericthornton** [FrontEndHappyHour/episode-ideas#2]
Hey guys - my episode idea is more audio-related than topic-related. All of the previous episodes have had good content - the trouble is actually hearing the majority of the panel. I know you all aren't professional podcasters, but if you could find a way to get more mics, it would help tremendously. I find myself having the volume cranked as high as it can go in order to hear everybody around the room and then my ears get destroyed when the one closest to the mic speaks. 

Keep up the good work and I look forward to more episodes.

**Comment by young** [comment]
Hey @ericthornton!
I totally agree. Our early audio sucked out loud but since then, we've spent quite a bit of money on microphones and lots (and lots) of editing time trying to improve the audio quality. I'd love to hear your feedback on some of our [newer](http://frontendhappyhour.com/episodes/transpilers-slow-down-and-drink/) episodes. Thanks for listening!

-Jem

**Comment by ryanburgess** [comment]
Thanks for the feedback @ericthornton! We appreciate you sticking with us and we'll continue to improve the quality of the audio. @young is right, we've invested in more mics and we're spending more time editing. Hopefully you're able to notice a difference.

I'm going to close this issue.

**Comment by ericthornton** [comment]
@ryanburgess and @young - yes the audio quality has definitely improved. at this point, it's just the occasional panel member slightly too far away from the mic, but even professionals do that from time to time. again, keep up the good work. 

![](http://i.giphy.com/l3E6z6QxD2uKoRTDq.gif)
